### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by bayaderpack** [willpinha/daisy-components#95]
### For which tag?

website

### For which UI example?

website

### Description

Website is down I cant reach it at all

### Do you want to contribute to this issue?

No, I will leave the issue to another contributor

**Comment by willpinha** [comment]
Hi, I'm sorry about that! Lately I tried to reimage the repository, but I ended up giving up. The current link reflects this change, but the deployment is not being done on it. I will update the repository information. For now, you can access the components through [this link](https://collection.willpinha.link)
